spring.application.name=project-one-colaboration-team

spring.datasource.url={{database_connection_url}}
spring.datasource.username={{database_username}}
spring.datasource.password={{database_password}}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.mail.host={{mail_server_host}}
spring.mail.port={{mail_server_port}}
spring.mail.username={{mail_account_username}}
spring.mail.password={{mail_account_password}}
spring.mail.properties.mail.smtp.auth={{smtp_authentication_enabled}}
spring.mail.properties.mail.smtp.starttls.enable={{starttls_enabled}}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true