spring.application.name=project-one-colaboration-team

spring.datasource.url=jdbc:postgresql://ep-little-star-aijf7kdh-pooler.c-4.us-east-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_WYRkfS5dC9Fn
spring.datasource.driver-class-name=org.postgresql.Driver
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=developdeivy@gmail.com
spring.mail.password=zhum ssfw zumy woye
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
